allowBuilds:
  '@swc/core': true
  esbuild: true
  mongodb-memory-server: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - mongodb-memory-server
  - sharp
  - unrs-resolver
